-- Identify Out-of-range dates
SELECT DISTINCT 

BDATE
FROM 
    silver.erp_CUST_AZ12
    WHERE BDATE < '1924-01-01' OR BDATE > GETDATE()


--- STANDARDIZATION

SELECT DISTINCT 
GEN,
CASE WHEN UPPER(REPLACE(REPLACE(REPLACE(TRIM(GEN), CHAR(160), ''), CHAR(13), ''), CHAR(10), '')) IN ('F','FEMALE') THEN 'Female'
     WHEN UPPER(REPLACE(REPLACE(REPLACE(TRIM(GEN), CHAR(160), ''), CHAR(13), ''), CHAR(10), '')) IN ('M','MALE')   THEN 'Male'
    ELSE 'N/A'
  END AS GEN
FROM silver.erp_CUST_AZ12
